[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[functions]
        node_bundler = "esbuild"

    [[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
